services:
  ea-account-service:
    container_name: ea-account-container
    image: ea-account-service
    build: ./
    restart: on-failure
    ports:
      - "8066:8066"

networks:
  default:
    external:
      name: ea-services-docker-network

#Network: Make sure the network gm-services-docker-network is created and available:
#docker network create g4m-services-docker-network